### ISSUE TITLE
(Tagged) Hashing and Signing by Oracle of Message

### ISSUE THREAD

**Issue by nkohen** [discreetlogcontracts/dlcspecs#111]
As @LLFourn mentions [here](https://github.com/discreetlogcontracts/dlcspecs/pull/55#discussion_r515442902), we need to specify a signing algorithm which includes a tagged hash for oracles signing messages.

We also need to decide what goes into this signed message other than just the outcome (e.g. the event id as well?)

**Comment by benthecarman** [comment]
Concept ACK!!

Imo we should be using tagged hashes for the outcome and the announcement.

Ideally we should have a version number in the tag as well as maybe use a different tag for different event types (ie `DLCv0Announcement`, `DLCv0EnumOutcome`, `DLCv0DigitDecomp`, etc)

> We also need to decide what goes into this signed message other than just the outcome (e.g. the event id as well?)

If the goal of this is to not have the same pre-images for differing events, then maybe just adding in the nonce (or hash of) would be the easiest.

**Comment by LLFourn** [comment]
Oops I seem to have missed these comments before looking at the PR. It's probably better to continue here.

> If the goal of this is to not have the same pre-images for differing events, then maybe just adding in the nonce (or hash of) would be the easiest.

Ah this addresses my query on the PR. The goal of including the event_id in there is so you can use the signature without having the announcement and learn a fact about the past. e.g. `US_election_2020_Trump_v_Biden=Biden_win`. If you just have `Biden_win`  you don't know just from the signature and message whether Biden won the presidential race or Friday night Bingo. If you have `US_election_2020_Trump_v_Biden=Trump_win` then you already have everything you need to show fraud. 

> Ideally we should have a version number in the tag as well as maybe use a different tag for different event types (ie DLCv0Announcement, DLCv0EnumOutcome, DLCv0DigitDecomp, etc)

As I said in PR I think we shouldn't use tags this way. I think we should just have one tag for all oracle signatures and domain separate separate different kinds of oracle signatures in the message itself. Having different tags means to anticipate signatures I have to cache around tagged hashes for all these tags to be maximally efficient.

On the subject of tagged hashes -- Jonas has put together a PR making variable length messages possible: https://github.com/bitcoin-core/secp256k1/pull/844 which would remove the need for tagged hashes altogether. You can just prefix the message with a 64 byte tag which would make things much simpler.
