### ISSUE TITLE
Starting a rust-dlc implementation

### ISSUE THREAD

**Issue by ariard** [discreetlogcontracts/dlcspecs#17]
Rust is awesome. Rust-bitcoin ecosystem is more than awesome. Starting a rust-dlc implementation laying on top of rust-bitcoin library would be great with same coding style, testing framework, review process. Smooth integration with rust-lightning should be targeted when this stuff is going to be off-chain.

**Comment by Tibo-lg** [comment]
We have started work on a rust implementation, will keep you updated once something is ready to review.

**Comment by ariard** [comment]
Cool, @rrybarczyk you were inteerested by DLCs IIRC :)  ? You should keep an eye here.

**Comment by dr-orlovsky** [comment]
@Tibo-lg feel free to make it (if you'd like) a part of LNP/BP library https://github.com/LNP-BP/rust-lnpbp built on top of rust-bitcoin: I will be happy to help with the code, review PRs and have a separate `dlc` mod there

**Comment by Tibo-lg** [comment]
@dr-orlovsky that sounds like a great idea. For now @yancyribbens is working on functions for transaction creation, once there is something to review we'll make a PR.

**Comment by ariard** [comment]
@dr-orlovsky host it directly under rust-bitcoin org, you will attract more eyes for review :)

**Comment by dr-orlovsky** [comment]
@ariard good idea, was thinking to do the movement once LNP/BP library will have more finished functionality/at least one public release on crates.io thou, but if `rust-bitcoin` are welcome, why not to do it now?

**Comment by nkohen** [comment]
Closing as it has started and now has its own place for issue discussions :)
