### ISSUE TITLE
Ordering of Inputs and Outputs in transactions

### ISSUE THREAD

**Issue by benthecarman** [discreetlogcontracts/dlcspecs#18]
Currently, you can gain a fair amount of information from the ordering of the inputs and outputs in a DLC's transactions.

Right now, an observer is be able to tell that the beginning inputs of the funding tx belong the initiator, and the ending inputs belong to the recipient, they won't exactly know where it starts and stops but they will still be able to do a reasonable estimation, also they will know who's change address is whose.

To fix this, we'd want to shuffle the inputs and outputs in a deterministic way so the that 2 parties can build the funding tx independently, the best way to do that AFAIK would to have them both randomize the ordering using the same entropy.  We could make the `eventId` the entropy, but that is likely going to be calculable through public information. A possible solution could be to use, `SHA256(initiator toLocalCETKey | recipient toLocalCETKey)` as our entropy because it should be impossible for both to appear if both parties are not reusing keys. Other solutions are possible as well. 

If we want to avoid shuffling we could use [BIP 69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki) as it is much easier to implement. However, this could lead to creating a fingerprint for DLC transactions issues as there are likely not many txs that have `number of inputs >= 2`, `number of outputs = 3`, and BIP 69 complaint.

**Comment by ariard** [comment]
In practice, BIP69 has been disregarded due to the legitimate concern of creating 2 set of transactions: BIP69-compliant vs non-BIP69 ones. I see less the number of inputs and outputs as it can be a plausible Coinjoin tx.

If you use watchtowers at some point, using pubkeys included in any witnessScript that you may hand over to them may be a privacy leak (if both parties use the same/decryption key is dependent on a single-party broadcast) ?

Why not exchange per-DLC ephemeral pubkeys between parties and ECDH a shared secret from then and use some PRF to shuffle inputs/outputs ? (by the way do you assume a authenticated and encrypted transport between DLC parties?)

**Comment by nkohen** [comment]
I agree that, at least long term, BIP 69 is probably not the way to go with the DLC spec right now. I think we should probably merge both of your ideas and do an `ECDH` between the two party's `toLocalCETKey`s as this will give us better assurances than using the hash of public keys which are "safe" to share, this should also avoid the problems brought up by ariard about watch towers.

And to your question, we will likely be reusing authenticated and encrypted transport from lightning :)

**Comment by Christewart** [comment]
We should look into Lisa Neigut's transaction creation proposal and see if she has any word's of wisdom here. https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-January/002466.html

A response from her on BIP69: https://twitter.com/niftynei/status/1237535101509971968

**Comment by nkohen** [comment]
During our meeting we decided that this discussion is a little premature given the current state of specification and implementation and we have decided to table this discussion to a later time.

**Comment by ariard** [comment]
See as a future spec topic to solve : https://github.com/discreetlogcontracts/dlcspecs/pull/51#discussion_r467585736

**Comment by nkohen** [comment]
I think in the future we should do something like Lisa's `serial_id` proposal for allowing users to choose ordering without too much overhead

**Comment by nkohen** [comment]
A link for reference: https://github.com/niftynei/lightning-rfc/blob/1aa5dbe2987f0a0e79fa1d04718d91c6d01e07b2/02-peer-protocol.md#the-tx_add_output-message
