### ISSUE TITLE
Specify how an `eventId` should be calculated

### ISSUE THREAD

**Issue by benthecarman** [discreetlogcontracts/dlcspecs#20]
An `eventId` should be a unique identifier between the parties in the DLC. Ideally it should be deterministic and should be reliant on the contract as well, to best accomplish this it would likely need to be a hash of the [contract info](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#contract-information), [oracle info](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#oracle-information), the [timeouts/delays](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#cet-csv-delay), as well as some public keys from the participating parties whether it be each other's funding keys or maybe a lightning public key.

**Comment by Tibo-lg** [comment]
Ah sorry just opened #32 without noticing this one.

**Comment by nkohen** [comment]
After further thinking, I ended up proposing in #59 that this should be done the way it is done in lightning (by using the funding output with a temporary id, which I computed as the hash of the offer)
