### ISSUE TITLE
Think of edge case test cases similar to tx_valid.json/tx_invalid.json and script_tests.json

### ISSUE THREAD

**Issue by Christewart** [discreetlogcontracts/dlcspecs#30]
Here are examples of how bitcoin core does this with testing script and transaction validity. Here are the examples: 

https://github.com/bitcoin/bitcoin/tree/master/src/test/data

Initial corner cases I can think of revolve around _both_ positive _and_ negative test cases for

- timeouts cases 
- fees

**Comment by Tibo-lg** [comment]
Some random test cases:

## Utxo Cases

* Case where each party has a single UTXO
* Case where one party has multiple UTXO
* Case where each party has multiple UTXO

## Change case

* Case where both parties have a change output
* Case where only one party has a change output
* Case where none of the parties have a change output

We might also want to distinguish between the cases where the change is exactly zero or when it is dust (though we need to decide on #11 first)

## CET cases

* Case where none of the outcome contain dust
* Case where some outcomes contain dust (for both parties)

## Outcomes

* Case with single message outcome
* Case with multiple messages outcome (multiple oracle signatures)
