### ISSUE TITLE
Event ID generation

### ISSUE THREAD

**Issue by Tibo-lg** [discreetlogcontracts/dlcspecs#32]
We need a way to uniquely identify DLC so that parties can establish multiple contracts concurrently and implementation can easily distinguish them at application and protocol level.

As discussed, it would be better to have the ID be generated from the beginning, so by the offering party, and using the offering party's public keys as these should not be reused across contract.

A proposal would thus be to have:
```
EventID = SHA256(localFundKey + localSweepKey + OraclePubKey + MaturityTime)
```

It might be enough to use only the public keys, but if the contract is canceled the local party might want to reuse the key (probably not a good idea, but not sure it is a good idea not to handle this case either).

**Comment by benthecarman** [comment]
It probably should include the a representation of the contract info in case an implementation reuses keys and they are doing 2 contracts with the same oracle and same MaturityTime (ie Price of BTC/USD at end of day and Price of LTC/USD at end of day)

**Comment by Tibo-lg** [comment]
The issue is that we haven't really described how the contract info look like yet. Maybe the best is just to leave that open for now and come back to it once we really need it.

**Comment by benthecarman** [comment]
Another option could be using the Oracle's R value instead of the contract info, that should be unique for every event

**Comment by nkohen** [comment]
See https://github.com/discreetlogcontracts/dlcspecs/issues/20#issuecomment-673717645
