### ISSUE TITLE
Privacy not guaranteed against mempool observer

### ISSUE THREAD

**Issue by LLFourn** [discreetlogcontracts/dlcspecs#35]
The DLC paper is ambiguous about key generation and the most straightforward interpretation of it is   vulnerable to rogue key attacks. The original DCI spec was not vulnerable to rouge key attacks but breaks a key privacy guarantee (see https://github.com/mit-dci/dlcspec/issues/5). To their credit, the authors of this spec seem to have understood that and has mitigated the issue to some extent, but not completely.

Each party has its own contract execution transaction that it can broadcast upon the completion of any event. If both parties broadcast such a transaction (which presumably is what is meant to happen?) then any observer of both transactions can identify the `Oracle Signature Point`.

This is what the CET looks like in the spec atm:

```
OP_IF
  <Oracle Signature Point + Local Funding Public Key + SHA256(Local Sweep Public Key)*G>
OP_ELSE
  <Timeout> OP_CHECKSEQUENCEVERIFY OP_DROP
  <Remote Sweep Public Key>
OP_ENDIF
OP_CHECKSIG
```
Any observer who sees both contract execution transactions will be able to determine what the `Oracle Signature Point ` is seeing as they can figure out `Local Sweep Public Key` from the other transaction and they know ` Local Funding Public Key` from the funding output.

My recommendation is to use a completely unrelated key to add to the `Oracle Signature Point` in the CET and provide a proof of knowledge on it (a Schnorr signature under it suffices).

**Comment by Tibo-lg** [comment]
Thanks for raising this concern. First maybe in case you hadn't followed this, @nkohen came up with the current spec after the discussion in #10.

> If both parties broadcast such a transaction (which presumably is what is meant to happen?) then any observer of both transactions can identify the Oracle Signature Point.

In my personal understanding, this is not meant to happen. In a normal execution case where both parties are online and able to communicate, they would create and sign a mutual closing transaction. I think only if both parties think the other is not online would they end up both broadcasting their CET.
The solution you propose came up in the discussions, but as it increases the protocol complexity we went with the current approach. I personally don't mind revisiting this issue if there is a concern.
I also proposed back in #10 to just use a value known by both parties to use as a tweak instead of the sweep key, do you see any issue with that (especially I wonder if there could be an issue if the value is chosen by one of the party)? It would reduce verification complexity.

> To their credit, the authors of this spec seem to have understood that and has mitigated the issue to some extent, but not completely.

IIRC you're the one who pointed the issue to us in the first place so I'd say the credit goes to you :)

**Comment by LLFourn** [comment]
Thanks for the link to the background discussion. I understand the CET broadcast now. Despite this it's usually better to guarantee properties like privacy to in the simplest way possible without such assumptions. Though, engineering complexity is certainly a concern so I happily leave the outcome of this ticket to the developers :)

> I also proposed back in #10 to just use a value known by both parties to use as a tweak instead of the sweep key, do you see any issue with that (especially I wonder if there could be an issue if the value is chosen by one of the party)? It would reduce verification complexity.

Yes. I think each party choosing their own tweak would also work. But I guess they would need a different one for each CET so they could send a seed and derive it.

I have no strong feelings about keeping this issue open -- I just wanted to point this out as I didn't know it had been discussed.

**Comment by Tibo-lg** [comment]
> Yes. I think each party choosing their own tweak would also work. But I guess they would need a different one for each CET so they could send a seed and derive it.

Ah what I meant was have one party choose a single tweak (e.g. just a random value). I'm not sure I see a point in having a different one for each CET though?

**Comment by LLFourn** [comment]
> Ah what I meant was have one party choose a single tweak (e.g. just a random value). I'm not sure I see a point in having a different one for each CET though?

I'm not sure either but it just seemed easier to prove secure that way. If each CET randomness is related then someone who sees two CETs can probably subtract away the randomness and get the sum of two oracle points and then learn the outcome that way. This would need to be two different CETs on two different oracle points. That obviously seems unlikely but as I said. it's usually better to prove privacy without resorting to reasoning about certain edge cases.

**Comment by Tibo-lg** [comment]
Mmmm I'm getting a bit confused then in what was your proposal. My understanding was that you wanted to replace:
```
<Oracle Signature Point + Local Funding Public Key + SHA256(Local Sweep Public Key)*G>
```
by
```
<Oracle Signature Point + Local Unrelated Public Key>
```
Is that correct? Or do you then want to have a single key for each CET? Like:
```
<Oracle Signature Point + Local Unrelated Public Key_i>
```

If that's the case, it doesn't sound realistic to me, as this would mean potentially having to generate and verify thousands of signatures (it's not unfeasible, but certainly impractical). 

If you meant the single key case, I don't see a difference between "someone who sees two CETs" and "someone who sees the unrelated public key". 

It is also possible to exchange a seed to use for generating a random value per CET, but again, if the seed is leaked, it's pretty similar to me as leaking two CETs. 

Sorry if maybe I am just misunderstanding something?

**Comment by LLFourn** [comment]
@Tibo-lg You're right. So the model is either: 
1. The adversary gets all CETs from both parties and all oracle points and has to guess which set of oracle points is being used.
2. The adversary gets two CETs on the same oracle point (one from each party).
3. The adversary gets only one CET.

The current impl is secure in scenario (3). But not in (2) or (1). It seems like a protocol secure in (2) should exist (adding fixed randomness as you suggested should do it). I think deriving different randomness for every CET from a seed should be secure in (1). Having said that (1) is not very realistic. 

> It is also possible to exchange a seed to use for generating a random value per CET, but again, if the seed is leaked, it's pretty similar to me as leaking two CETs.

If a party is leaking private info to the adversary then there's no chance of privacy in any case I think.

**Comment by Tibo-lg** [comment]
>>It is also possible to exchange a seed to use for generating a random value per CET, but again, if the seed is leaked, it's pretty similar to me as leaking two CETs.

> If a party is leaking private info to the adversary then there's no chance of privacy in any case I think.

The point I was trying to make is that in my view leaking two CETs (from a single party) means leaking private information. One might maybe argue that it's easier to secure a seed than a set of transactions, not sure how valid an argument that would be.

But let's assume we go for sharing a seed used to generate different tweaks for each CET, would that solve (1) (2) and (3)? (I can't see a way to recover the oracle point without knowing the seed personally but maybe one needs to spend a bit more time considering potential issues).

I think we can summarize the possible solutions as:
1. Don't change anything, and consider that having both party broadcast their CET is too much of a corner case to be worth caring for,
2. Exchange new public keys between the party together with a signature proving knowledge of the private key,
3. Use a single random value to tweak the `oracle point + fund public key` that is shared e.g. in the offer message (we could discuss later how this get generated),
4. Use a seed to generate distinct tweak values for each CET.

I personally think that 3 is a good and simple solution that solves the problem in the realistic cases, but I've ranted enough and will let others give their opinions.

**Comment by Ichiro0219** [comment]
Thanks for raising this concern @LLFourn .
As you point out, if a malicious enemy is able to steal two CETs (or both party broadcast their CET), the Oracle Signature Point will be calculated and the contract will be known.

IMHO, we don’t need to change spec because
・Having multiple CETs known is equal to leaking privacy, and having both party broadcast their CET is not usual case (same idea as @Tibo-lg )
・If we create thousands of CETs (ex financial trading), creating tweaks for each CET seems to be complicated for managing it (The complexity is mitigated by using seed although)

If I've missed any points, please let me know.

**Comment by LLFourn** [comment]
> and having both party broadcast their CET is not usual case (same idea as @Tibo-lg )

Isn't it something that a malicious party could induce by interrupting the connection between the two parties? How hard would it be to trigger two CETs being released if you're a man in the middle?

> I personally think that 3 is a good and simple solution that solves the problem in the realistic cases, but I've ranted enough and will let others give their opinions.

FWIW I agree :+1:

**Comment by nkohen** [comment]
I also think 3 is probably most feasible, and to the earlier discussion I do think that although there is an inherent privacy leak when two parties broadcast CETs, it is not nearly as bad a leak if oracle points aren't revealed, so we should protect against this.

What are people's thoughts on using something like the ECDH of funding keys? Secure against rogue key attacks?

**Comment by Tibo-lg** [comment]
> What are people's thoughts on using something like the ECDH of funding keys? Secure against rogue key attacks?

If there is no downside to this I'd say this is the most elegant solution, but just to make sure we are on the same page, would we then have something like:
```
<Oracle Signature Point + ECDH(Local/Remote Fund key) >
```

**Comment by LLFourn** [comment]
I think @nkohen  means:
<Oracle Signature Point + Local Funding Public Key +  Sha256(ECDH(Local/Remote Fund key))*G >

This will work. I'm not sure it provides any improvement over one party just sending a random 32 bytes so I guess it could be preferable from an engineering standpoint (less stuff in message).

**Comment by nkohen** [comment]
I believe this discussion is now void due to our move to adaptor signature based DLCs which have none of these problems. This issue may once again become relevant however when we get around to specifying how to combine oracles.
