### ISSUE TITLE
Standardizing URI for an oracle on an http server

### ISSUE THREAD

**Issue by Christewart** [discreetlogcontracts/dlcspecs#45]
This was a debate on the #42 and is closely related to #44 

My understanding, correct me if I'm wrong, is how do we "find" information that an oracle server has. Also can their be compatibility across similar events such as a basketball game and a tennis match

**Comment by Christewart** [comment]
Here is information related to our API which is out of date a bit: https://test.suredbits.com/api/#discreet-log-contract-dlc-oracles

**Comment by Tibo-lg** [comment]
Documentation for our API can be found here: https://github.com/p2pderivatives/p2pderivatives-oracle/tree/develop/api

Subject to change though :)

**Comment by Christewart** [comment]
> Documentation for our API can be found here: https://github.com/p2pderivatives/p2pderivatives-oracle/tree/develop/api
> 
> Subject to change though :)

I thought it was .... wait for it.... on the blockchain though? 

Ok i'm done with my bad jokes :-) :-)
