### ISSUE TITLE
Partition of Specification and Assignment

### ISSUE THREAD

**Issue by nkohen** [discreetlogcontracts/dlcspecs#46]
On this issue I would like to discuss how we want to partition [the spec outline](https://dynalist.io/d/TlMSefaI7Uq4hE4M9bykU2Mh) into files/modules and subsequently decide who is going to write what.

I think the following high-level module separation makes sense:

- Oracle Requirements (as in things oracles MUST do, not SHOULD, such as provide R values)
- Oracle Best Practices/Standards
- Contract Negotiation
- Transaction Specification
- Signing Protocol (with verification steps included)
- Contract Execution (state machine?)

Perhaps we want something even more granular than this? And/or modifications to this? Please leave your opinions here.

Follow-up question: How do people feel about breaking up large documents into smaller ones contained in folders, e.g. Transaction Specification is a folder containing separate documents for funding transaction, CETs, Refund transaction, rather than having all of these things in a single file.

**Comment by LLFourn** [comment]
I think ECDSA adaptor signatures in their own file similar to BIP340.

**Comment by ariard** [comment]
I agree with Lloyd let put adaptor signatures in its own file section but integrate verification steps as part of contract negotiation. Negotiation can be meltdown with off-chain execution as BOLT 3 is doing.

We could have an onchain ("what should you do when you see an invalid CET onchain ?") section, as this one is only concerning a participant and observed onchain transactions, not at all counterparty. It's really a different flow than exchanging off-chain peer messages to advance contract state.

A section on contract discovery/contract offers ?

> How do people feel about breaking up large documents into smaller ones contained in folders, 

I think for now it's better to let everything in one file, especially for transactions as some subsection are factorized over the whole, like fee computation.

**Comment by Tibo-lg** [comment]
@nkohen I'm not sure I get what does contract negotiation entails?

> A section on contract discovery/contract offers ?

@ariard While I think this is really nice to have, I'm not sure that should be part of v0.1.

**Comment by nkohen** [comment]
> @nkohen I'm not sure I get what does contract negotiation entails?

I think by contract negotiation we mean the handshake:
```
Offer ->
      <- Accept
Sign  ->
```

**Comment by Tibo-lg** [comment]
Ok thanks and then what is the difference with the Signing protocol? Is that more about generating the signature themselves locally?

**Comment by nkohen** [comment]
> Ok thanks and then what is the difference with the Signing protocol? Is that more about generating the signature themselves locally?

Yeah I think the suggestion that we are all agreeing on is to have a separate spec file in the vein of BIP 340 which specifies our variant of ECDSA adaptor signatures

**Comment by nkohen** [comment]
I believe pretty much all the work discussed here is done or assigned and in progress
