### ISSUE TITLE
Adaptor signature documentation / explaination

### ISSUE THREAD

**Issue by Christewart** [discreetlogcontracts/dlcspecs#50]
I think we should add some documentation on the repo about our choice to use adaptor signatures and what variant we are using with links to more extensive documentation on what they are. They are a core piece of how the DLC protocol works and aren't widely adopted in the ecosystem (yet), so it's a good idea to make sure we explain these. A 3rd party reading the DLC spec for the first time may not even be aware of what they are.

This is probably a subtask of #46

**Comment by LLFourn** [comment]
I don't mind doing this but I'd rather do the specification and description in one go since we'll learn as we go and develop a terminology around it as we use it. So maybe after we've played around with implementation a bit?

**Comment by LLFourn** [comment]
Update on this. I am working on how to specify these types of proofs in another project as well. I am not aware of other attempts to specify a sigma protocol around Bitcoin so I would like to set a good precedent for how to do it properly that can be reused by independent protocols and be composed in larger proofs. My goal is to avoid specifying a "DLEQ" proof per se but to instead just specify how to do a DL proof and then how to do an EQ proof for two instances of a sigma protocols for the same type of relation. Then finally how to make them non-interactive.

DLEQ proofs have other applications and there are also people working on doing a cross curve DLEQ between ed25519 and secp26k1 to which this work will also be applicable.
My goal is not too ambitious just enough to avoid repetition of both code and specification across projects.

I have barely started working on and I don't think it will be in a specifiable state until the end of next week at the earliest. Will need some review first from @jonasnick, @AdamISZ and @luckysori too.
