### ISSUE TITLE
Oracle Info TLV Specification

### ISSUE THREAD

**Issue by nkohen** [discreetlogcontracts/dlcspecs#61]
We need standard ways of serializing Oracle Info in our P2P messages (see #59).

I foresee that there will be many different oracle info types including

- Oracle with single R value
- Oracle with multiple R values
- Multiple oracles (n-of-n)
- Multiple oracles (m-of-n)

and likely more in the future. As such, I propose we use different TLV types for these different cases.

To allow test vectors to be written and development to begin without being blocked on this, I also propose type `0` oracle information to be a single oracle with a single R value serialized as the concatenation of the oracle signing key and the R value (32 bytes each for a total of 64 bytes + type and length prefix).

**Comment by LLFourn** [comment]
I am not following the design of the p2p layer closely but I have some queries on this.

The oracle signing key is to identify the oracle right (It is not actually used by the other party)? Why would you send the R values; Shouldn't they just fetch them themselves?
If you are saying parties may send the oracle announcement message (signed by the oracle themselves) with its R values(s) then that's a nice idea but then I think the serialization should just be the announcement message itself.

**Comment by nkohen** [comment]
The current `v0` type is to help get development off the ground while oracle discussions are still in flux, it allows for the construction of DLCs for testing and manual play, in the future I assume better types will be introduced that make more sense and are more robust
