### ISSUE TITLE
Contract Info TLV Specification

### ISSUE THREAD

**Issue by nkohen** [discreetlogcontracts/dlcspecs#62]
We need standard ways of serializing Contract Info in our P2P messages (see #59).

I foresee that there will be many different contract info types including

- Map from outcome hashes to values
- Ranges of outcomes to values
- Map from multiple outcome hashes and/or ranges to values

and likely more in the future. As such, I propose we use different TLV types for these different cases.

To allow test vectors to be written and development to begin without being blocked on this, I also propose type 0 contract information to be a the number of outcomes, followed by `(32 byte hash || 8 byte value)` pairs for each outcome.

**Comment by benthecarman** [comment]
To do #40 we will eventually want to be able to define or reference oracle infos with each outcome

**Comment by nkohen** [comment]
https://github.com/discreetlogcontracts/dlcspecs/pull/59#discussion_r471774033
