### ISSUE TITLE
Initiator gives free option to acceptor of DLC after signing

### ISSUE THREAD

**Issue by Christewart** [discreetlogcontracts/dlcspecs#68]
From @nicolasdorier on slack

>btw, if the funding transaction is not broadcast immediately after the initiator sent the SIGN message, he needs to double spend to himself the funding coin

**Comment by ariard** [comment]
Yes same concern that pinning scenario we previously discussed. I'll address with the non-interactive part of the protocol.

Note, however that "broadcast immediately" could not be observable by a node depending of your mempool configuration, network connectivity. Better to give a block delay, then do whatever you can to double-spend your coins.

**Comment by nkohen** [comment]
Closed by #87
