### ISSUE TITLE
Key Derivation Concerns

### ISSUE THREAD

**Issue by benthecarman** [discreetlogcontracts/dlcspecs#8]
I have some concerns with the current way the DLC spec outlines how to do key derivations. From my understanding, we are sending extended public keys because if we have 100 possible outcomes, we don't want to pass 101 pubkeys (100 outcomes + timeout).

However, using extended public keys will likely break compatibility with most, if not all, wallets that are not aware of the DLC spec. This is because we are using the [account path](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account), as the `event_id`. This will likely break [traditional account discovery](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery). 

For example, if I have a DLC with `event_id = 21` a wallet using traditional account discovery will not find transactions related to these DLCs unless my wallet already has used accounts 0 through 20.  A possible solution could be to have both parties give the `event_id` they will be using so the wallet can find the relevant keys, however there can still be some problems with this as the funding key exists at `m / purpose' / coin_type' / event_id' / 0` and most wallets will be looking at the `address_index` level, not the `change` level.

Another possible issue is that the current schema makes it impossible to have it so your winnings are being sent to another party, as you must be able to sign with the parent keys.

Curious on your guys' thoughts and open to discussion about this.

EDIT 2/11/20:

Discussed this further with @nkohen @Christewart

Another issue that arises is a wallet's gap limit. If I execute a DLC that has 100 outcomes and my 99th key is used for that outcome, most wallets will not find the transaction because the 98 keys before will not have any txs so the gap limit would need to be at least 99 to see them.

In my mind there are only 2 real solutions to these problems.

1) Send over all keys: This solves all the above issues besides the address gap limit problem, wallets could then just pick the next _N_ keys and make sure they are tracking all of those. However, if their gap limit is less than _N_ they would need to know that a dlc was executed that used all _N_ keys.

2) Change spec to only use 8 keys: This solution should solve all the problems.
For this solution you would have 1 funding key, 1 refund key, 3 cet keys and 3 closing keys. That way with 8 keys you will most likely be under every wallets gap limit and can easily be bip44 compliant. As an example, for my wallet if `m/89'/0'/'0'` is my account and `/0/20` is my next open key we'd send over the keys corresponding to `/0/20` - `0/27` for all the dlc keys. This also would allow more extensibility for wallets so they could choose to have dlc cets execute in a separate account but all the funds are sent to and from a main account or whatever weird schema they want to implement for their users.

**Comment by benthecarman** [comment]
The main point of this issue is that the current  spec is the best way to do it if there was no existing standards. However, for the most adoption of dlcs we need wallets to have the ability to easily implement tracking of dlcs funds.

**Comment by Tibo-lg** [comment]
I think you have a point, and the solution 2 seems good to me. It will actually make implementation a bit simpler and I cannot see any drawback.

**Comment by benthecarman** [comment]
Thinking about this a little more if we are just doing 8 keys, we can just do 5 pubkeys + 3 script pub keys for the closing txs

**Comment by Christewart** [comment]
If we do go with 2, we need explicit steps to fail the DLC setup if we cannot verify that our keys are apart of the keychain we sent over. I.e. they are not using the proper indexes.

**Comment by Tibo-lg** [comment]
@Christewart Maybe I misunderstand what you mean, but I think since each party (re)builds the transactions, it would probably fails on signature verification if an issue with key derivation arises.

**Comment by nkohen** [comment]
So I just implemented solution two on a branch on our end and we only need 4 keys not 8:

1. Funding Key = /0/0
2. CET ToLocal Key = /0/1
3. CET ToRemote Key = /0/2
4. Final Key = /0/3

where ToLocal Key is reused across both parties versions for normal sweep and penalty cases respectively, and Final Key is used to sweep, mutual close, and refund.

**Comment by benthecarman** [comment]
Closed by #10
