### ISSUE TITLE
Transaction output ordering

### ISSUE THREAD

**Issue by dr-orlovsky** [discreetlogcontracts/dlcspecs#84]
Right now transaction outputs have a fixed order (https://github.com/discreetlogcontracts/dlcspecs/blob/master/Transactions.md#funding-transaction-input-and-output-ordering). While this is very good for applications like RGB (public key tweaking with certain very low probability may break ordering), it is against BIP 69 (lexicographic ordering of transaction inputs and outputs) and reduces privacy (DLC transactions can be detected with onchain analysis by their output order fingerprint.

**Comment by nkohen** [comment]
Discussion of this is [here](https://github.com/discreetlogcontracts/dlcspecs/issues/18) :)
